### ISSUE TITLE
english language support

### ISSUE THREAD

**Issue by kejfel** [dominikwinter/mobile-scraper#3]
Is that possible, to process all the common things in english.

**Comment by dominikwinter** [comment]
Hi, good idea! I created a new PR #4. Maybe you can test it, if you like :)

**Comment by kejfel** [comment]
Hi, I've tried and faced this bellow issue on Win 10. 
Yesterday worked on OSX, I can try aggain on it afternoon.

~~~~~~~~~~~~~~~~~~~~~~~~~
npm  install
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm notice created a lockfile as package-lock.json. You should commit this file.
added 160 packages in 62.651s
~~~~~~~~~~~~~~~~~~~~~~~~~
INFO _parseItemPage
module.js:665
    throw err;
    ^

SyntaxError: C:\Users\kejfel\dev\mobile-scraper\.cache_en\250486881.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:662:27)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at items.forEach (C:\Users\kejfel\dev\mobile-scraper\index.js:266:29)
    at Array.forEach (<anonymous>)
    at fs.readdir (C:\Users\kejfel\dev\mobile-scraper\index.js:265:19)

**Comment by dominikwinter** [comment]
"Unfortunately" I have no Windows :)
Can you show me the content of `C:\Users\kejfel\dev\mobile-scraper\.cache_en\250486881.json`?

**Comment by kejfel** [comment]
Working fine on OSX 10.13.3! Thank you!
I can send it tomorrow.

**Comment by dominikwinter** [comment]
Hmm ... OK, that's funny :D 

I have tried to make the code more robust, with a bit more error handling.
Can you try it again, please? :)

**Comment by kejfel** [comment]
Sorry for delay, that JSON issue is still exist but was able to export a corrupt file.

last GET
SEARCH GET https://suchen.mobile.de/fahrzeuge/search.html?language=en&ambitCountry=DE&zipcode=35390&zipcodeRadius=55&categories=EstateCar&isSearchRequest=true&scopeId=C&damageUnrepaired=NO_DAMAGE_UNREPAIRED&minF
irstRegistrationDate=2016-01-01&maxMileage=50000&maxPrice=24000&adLimitation=ONLY_DEALER_ADS&makeModelVariant1.makeId=16800&makeModelVariant1.modelId=4&fuels=PETROL&fuels=HYBRID&minPowerAsArray=150&minPowerAsArr
ay=PS
CAR GET https://suchen.mobile.de/fahrzeuge/details.html?id=257814903
Couldn't load file ./.cache_en/254305332.json. SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at items.forEach (C:\Users\I328096\dev\mobile-scraper\index.js:254:40)
    at Array.forEach (<anonymous>)
    at fs.readdir (C:\Users\I328096\dev\mobile-scraper\index.js:252:19)
    at FSReqWrap.oncomplete (fs.js:135:15)
Cars found: 31
Output: excel_en.xls

JSON is same 0kb.

![image](https://user-images.githubusercontent.com/11033682/36301120-086ff2ee-1304-11e8-8503-c627bbceffcd.png)

![image](https://user-images.githubusercontent.com/11033682/36301367-d52d1c58-1304-11e8-94a6-8cfc7b12d47f.png)

**Comment by dominikwinter** [comment]
Hi, thanks for your response. Actually I don't know why the JSON file is corrupt .. but anyway the the Excel file could generated. Maybe it could help to remove the `.cache_en/` directory.

The message from Excel can be ignored, I think. With OpenOffice there is no warning :D

I would merge this branch to master if there are no further issues left :)

**Comment by kejfel** [comment]
OK! :) Thnx the soultion!
